### ISSUE TITLE
[Bug][Linux][0.0.6] Unable to launch script

### ISSUE THREAD

**Issue by thefinaldegree** [rnayabed/streampi_server#15]
OS: Ubuntu 20.04
Stream Pi Server: 0.0.6
Stream Pi Client: Android 0.0.6

Attempting to run a script that's assigned to a button causes the following error:
```GOT @ 99
script::<>/path/to/scripts/script.sh<>::action_119191::df
'script'
Running "" "/path/to/scripts/script.sh"
java.io.IOException: Cannot run program ""/path/to/scripts/script.sh"": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at StreamPiServer.dashboardController$4.call(dashboardController.java:1266)
	at StreamPiServer.dashboardController$4.call(dashboardController.java:928)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 10 more
12112
SENT @ 43
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(Unknown Source)
	at StreamPiServer.dashboardController.lambda$showPushNotification$10(dashboardController.java:2064)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)```

And permissions on the script are set to allow anything to execute:
```[Sat Jan 30 05:23:51] user@pc:/path/to/scripts/$ ls
total 23K
drwxrwxr-x 2 user root 13 Jan 30 17:23 .
drwxrwxr-x 4 user root  4 Jan 30 16:57 ..
-rwxrwxr-x 1 user root 66 Jan 30 17:03 script.sh```

Let me know if there's any other information you need to help fix this bug

**Comment by rnayabed** [comment]
@thefinaldegree This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
